In [1]:
import pandas as pd,numpy as np,matplotlib.pyplot as plt , seaborn as sns
import os , sys
from sklearn.linear_model import LogisticRegression 

In [3]:
df = pd.read_csv('../data/cleaned_heart_disease.csv')

In [9]:
cat_cols = df.select_dtypes(include = ['object']).columns
print(cat_cols)

Index(['sex', 'dataset', 'cp', 'restecg'], dtype='object')


In [10]:
X = df.drop(columns = 'num')
y = df['num']

In [11]:
X = pd.get_dummies(X , columns = ['sex', 'dataset', 'cp', 'restecg'] , drop_first= True)

In [13]:
X.head(2)

,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,thal,sex_Male,dataset_Hungary,dataset_Switzerland,dataset_VA Long Beach,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality
0,63,145.0,233.0,True,150.0,False,2.3,0,2,True,False,False,False,False,False,True,False,False
1,67,160.0,286.0,False,108.0,True,1.5,3,1,True,False,False,False,False,False,False,False,False


In [16]:
cols = X.columns
print(len(cols))

18


In [20]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42 , stratify = y)

In [21]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [47]:
model = LogisticRegression(random_state= 42 , multi_class='ovr' , max_iter=2000 , class_weight = 'balanced')
model.fit(X_train_scaled , y_train)

C:\Users\sai charan\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,'balanced'
,random_state,42
,solver,'lbfgs'
,max_iter,2000
,multi_class,'ovr'


In [48]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score , confusion_matrix
y_pred = model.predict(X_test)

print(f"acc :{accuracy_score(y_test , y_pred):.4f}")
print(f"pre : {precision_score(y_test , y_pred , average = 'weighted'):.4f}") 
print(f"recall : {recall_score(y_test , y_pred , average='weighted'):.4f}")
print(f"f1score : {f1_score(y_test , y_pred , average = 'weighted'):.4f}") 
print(f"confusion matrix : {confusion_matrix(y_test , y_pred)}")

acc :0.2500
pre : 0.0802
recall : 0.2500
f1score : 0.1215
confusion matrix : [[ 0 80  0  0  2]
 [ 0 44  0  0  9]
 [ 0 20  0  0  2]
 [ 0 17  0  0  4]
 [ 0  4  0  0  2]]


C:\Users\sai charan\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\sai charan\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [28]:
print(y.unique())

[0 2 1 3 4]


In [31]:
print(y.unique())
print(y.value_counts())
print(X_train_scaled.shape)
print(X_test_scaled.shape)

[0 2 1 3 4]
num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64
(736, 18)
(184, 18)


In [36]:
X_train_scaled.mean()

np.float64(5.122043422787558e-17)

In [37]:
X_train_scaled.std()

np.float64(1.0)

In [38]:
print(X_train.dtypes.value_counts())

bool       11
float64     4
int64       3
Name: count, dtype: int64


In [49]:
correlations = X.corrwith(df['num']).sort_values()
print(correlations)

dataset_Hungary            -0.379413
thalch                     -0.349173
cp_atypical angina         -0.343266
chol                       -0.230539
restecg_normal             -0.168309
cp_non-anginal             -0.156050
cp_typical angina          -0.055896
trestbps                    0.113178
fbs                         0.129539
restecg_st-t abnormality    0.131698
dataset_VA Long Beach       0.241977
sex_Male                    0.259342
dataset_Switzerland         0.278355
thal                        0.310675
ca                          0.317337
age                         0.339596
exang                       0.350567
oldpeak                     0.411588
dtype: float64


In [50]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_test_scaled)
print(f"RF Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")

RF Accuracy: 0.6087


In [51]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train_scaled, y_train)

model = LogisticRegression(random_state=42, multi_class='ovr', max_iter=2000)
model.fit(X_train_balanced, y_train_balanced)

ModuleNotFoundError: No module named 'imblearn'